apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: test-build
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/johscheuer/go-hello-webserver.git
      revision: master
  template:
    name: kaniko
    arguments:
    - name: IMAGE
      value: docker.io/johscheuer/go-hello-webserver:latest
